# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitfolio" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3ed5755dd0bc3c851e756162496f15108f2a6857c1bc9855edc55677d3237239"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f24715fb123e46b8866b03241a72456d4f4ca490708ef7dcfb31b74d8d523e7"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de6d19178336c308c8b96085de59369ef766e492be30000f7d8a9cbd3ac7536c"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0547e295009f673cba34dbdf0453c44c3e5e9f366695f54f611414ef6ac20e3"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_amd64.tar.gz"
    end
  end

  name "gitfolio"
  desc "Turn your git history into a verified developer portfolio"
  homepage "https://aline.team"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitfolio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitfolio"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gitfolio init` to choose the repositories to collect.
  EOS
end
