# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitfolio" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "c7bb68346a05d12707cc7e4a8fba19abe67a05f82356bfd8e903067476fc7ecb"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "707d3dc90b9169b43d34c1dda034f42bbe0d9c75805d5c47e32917647bd8e3f0"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "80cb8e63f4a4042a101431f3adcf90486966c0d151bbe3302cd0ca2e590fa0f4"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4d78b7ff0ce99f217f160c7cc4104753d2b050b55d0ec4d3c62fb64134a27c3"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_amd64.tar.gz"
    end
  end

  name "gitfolio"
  desc "Turn your git history into a verified developer portfolio"
  homepage "https://aline.team"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitfolio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitfolio"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gitfolio init` to choose the repositories to collect.
  EOS
end
