# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitfolio" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gitfolio"]
    end
  end

  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "c2fab2a794a364577cef8f33e20f04ba8fe5c055d50ab3fd25d9c87f99f7a70b"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2307528b0fef1c5bbb2b81dcaf330c539bff685b6100acfae4b84fc6802572ab"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d60ab0d4d69847c1070a122b065d5bac6ae56802d1f52a326a0c74b919adeb83"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45e223db946cd2e9e07cd00f0c3bb7a020475383769d18866f1db060656f2182"
      url "https://github.com/Alineteam-Inc/GitFolio/releases/download/v#{version}/gitfolio_linux_amd64.tar.gz"
    end
  end

  name "gitfolio"
  desc "Turn your git history into a verified developer portfolio"
  homepage "https://aline.team"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitfolio"

  # No zap stanza required

  caveats <<~EOS
    Run `gitfolio init` to choose the repositories to collect.
  EOS
end
